### ISSUE TITLE
_SBBResourceList updateManagedObject crash

### ISSUE THREAD

**Issue by wbmd-sagarwal** [Sage-Bionetworks/Bridge-iOS-SDK#118] opened 2017-02-02 19:43 UTC
We are experiencing the crash while using class _SBBResourceList. 
- This crash occurred in ios 9.x after logging in using an existing username for the study identifier "stsi-preganancy"
- Error found in line: 209 in function: updateManagedObject: withObjectManager: cacheManager: 
Please let us know if you need any other information from our end.

Stack Trace:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSOrderedSet isSubsetOfSet:]: set argument is not an NSSet'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d681d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010cc31deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d6cb5cc -[NSOrderedSet isSubsetOfSet:] + 428
	3   Foundation                          0x000000010923d7c7 NSKeyValueWillChangeBySetMutation + 371
	4   Foundation                          0x00000001091b3a3e NSKeyValueWillChange + 383
	5   Foundation                          0x000000010923d5f1 -[NSObject(NSKeyValueObserverNotification) willChangeValueForKey:withSetMutation:usingObjects:] + 557
	6   CoreData                            0x000000010d27da17 _sharedIMPL_removeSet_core + 119
	7   BridgeSDK                           0x000000010c89a8f6 -[_SBBResourceList updateManagedObject:withObjectManager:cacheManager:] + 694
	8   BridgeSDK                           0x000000010c89a4ca -[_SBBResourceList createInContext:withObjectManager:cacheManager:] + 186
	9   BridgeSDK                           0x000000010c8fd9c2 __69-[SBBCacheManager cachedObjectOfType:withId:createIfMissing:created:]_block_invoke + 770
	10  CoreData                            0x000000010d210127 developerSubmittedBlockToNSManagedObjectContextPerform + 199
	11  CoreData                            0x000000010d20ffee -[NSManagedObjectContext performBlockAndWait:] + 222
	12  BridgeSDK                           0x000000010c8fd47e -[SBBCacheManager cachedObjectOfType:withId:createIfMissing:created:] + 990
	13  BridgeSDK                           0x000000010c8fe776 -[SBBCacheManager cachedObjectFromBridgeJSON:createIfMissing:] + 2246
	14  BridgeSDK                           0x000000010c8fde78 -[SBBCacheManager cachedObjectFromBridgeJSON:] + 72
	15  BridgeSDK                           0x000000010c8e1d3e -[SBBObjectManager objectFromBridgeJSON:] + 1390
	16  BridgeSDK                           0x000000010c8c3641 __97-[SBBActivityManager getScheduledActivitiesForDaysAhead:daysBehind:cachingPolicy:withCompletion:]_block_invoke_2 + 289
	17  CoreData                            0x000000010d210127 developerSubmittedBlockToNSManagedObjectContextPerform + 199
	18  libdispatch.dylib                   0x000000010fd963eb _dispatch_client_callout + 8
	19  libdispatch.dylib                   0x000000010fd7c82c _dispatch_queue_drain + 2215
	20  libdispatch.dylib                   0x000000010fd7bd4d _dispatch_queue_invoke + 601
	21  libdispatch.dylib                   0x000000010fd7e996 _dispatch_root_queue_drain + 1420
	22  libdispatch.dylib                   0x000000010fd7e405 _dispatch_worker_thread3 + 111
	23  libsystem_pthread.dylib             0x00000001100d34de _pthread_wqthread + 1129
	24  libsystem_pthread.dylib             0x00000001100d1341 start_wqthread + 13
)

**Comment by wbmd-sagarwal** [comment] 2017-02-02 19:43
@wbmd-pbeyer @wbmd-omokretsov

**Comment by Erin-Mounts** [comment] 2017-02-02 20:02
It seems to be something particular about your study setup or the user account that's triggering this bug, as I am unable to reproduce this. Can you put a breakpoint on the offending line and see what type the argument that's supposed to be a set actually is? Or is it just nil?

**Comment by wbmd-sagarwal** [comment] 2017-02-03 19:41
@wbmd-dho

**Comment by wbmd-dho** [comment] 2017-02-03 20:11
This issue seems to occur on 9.x

In the method updateManagedObject:withObjectManager:cacheManager: 

It appears that it is trying to remove an item. 

[managedObject removeItems:managedObject.items];  // <-- the offending line

the items property appears to be an NSOrderedSet but it is empty.

**Comment by wbmd-dnilsen** [comment] 2017-02-09 16:43
@Erin-Mounts This can be replicated with your sample app. Use our study identifier and login as existing user dnilsen20@yopmail.com. The password is Test123$. Also use iOS simulator iPhone 5s running 9.3. The crash should occur just after login.

**Comment by wbmd-dnilsen** [comment] 2017-02-09 18:10
@Erin-Mounts Actually this can also be replicated in the sample study using the above simulator and an existing user.

**Comment by Erin-Mounts** [comment] 2017-02-09 18:39
Turns out this is due to a longstanding iOS bug with CoreData generated accessors for ordered sets that was only finally fixed in iOS 10: http://stackoverflow.com/questions/7385439/exception-thrown-in-nsorderedset-generated-accessors

Assuming you don't want to just require a minimum iOS version of 10 for your app, I'll try to work around it.

**Closed** 2017-02-10 00:48 UTC

**Comment by Erin-Mounts** [comment] 2017-02-10 00:52
BridgeAppSDK is also now updated to reference this commit of Bridge-iOS-SDK.
